- name: Set up environment on development machine
  hosts: localhost
#  become: yes

  tasks:
    - name: Include main vars
      ansible.builtin.include_vars:
        file: vars.yml

- name: Include pre-req playbook
  ansible.builtin.import_playbook: pre-req.yml

#    - name: Update apt package list
      #      dnf:
#        update_cache: yes

    #    - name: Upgrade all apt packages
      #      dnf:
#        upgrade: dist

