- name: Set up environment on development machine
  hosts: localhost
#  become: yes

  tasks:
    - name: Update dnf package list
      dnf:
        update_cache: yes

    - name: Upgrade dnf packages
      dnf:
        upgrade: dist
