# Dockerfile for development testing
FROM fedora:40

# Install curl for downloading the setup script
RUN dnf update -y

# Update package list and install necessary packages
RUN dnf install -y ansible git

RUN mkdir ~/private

WORKDIR /home

RUN ls

# Keep the container running for interactive testing
CMD ["sleep", "infinity"]
